### ISSUE TITLE
Result<bool> that cannot return Ok(false)

### ISSUE THREAD

**Issue by Ekleog** [allenap/rust-postgresfixture#126]
Hey!

I was reading some more the docs, and noticed that eg. createdb and dropdb return `Result<bool, Error>`, but do not document what the bool actually means and upon reading the source code to figure it out can only ever return `Ok(true)`.

Why not make them just return `Ok(())`?

**Comment by allenap** [comment]
I think I did this for a couple of reasons:

- To be consistent with several other functions in `impl Cluster`.
- To one day return `false` when the database already exists (in `createdb`) or when the database didn't exist (in `dropdb`) without an API break. At present these will, I expect, crash in those situations.

Probably not the greatest of reasons, but I think it's okay to leave them for now.

**Comment by Ekleog** [comment]
Hmm if the database already exists / didn't exist I'd have expected these functions to return an `Err(Error::AlreadyExists)` or `Err(Error::NonExistent)`. Am I wrong?

As for the consistency argument, I'd argue that `create`, `start`, `stop` and `destroy` probably should also avoid replying `bool`, for the same reason as for createdb/dropdb; though it's less clear for `start` and `stop`

(Either way, whatever you choose doing, I think it'd deserve documenting what the `bool` actually means, it's not obvious which value means what otherwise :))

**Comment by allenap** [comment]
You're right, an enum would be better than a boolean.
