### ISSUE TITLE
createdb fails

### ISSUE THREAD

**Issue by Ekleog** [allenap/rust-postgresfixture#127]
Well, still on my way to try using postgresfixture, I'm hitting issues in createdb: it's returning the following error:
```
DatabaseError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42601), message: "syntax error at or near \"-\"", detail: None, hint: None, position: Some(Original(21)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1176), routine: Some("scanner_yyerror") }) })
```

I have literally no idea how to interpret that, but my guess would be it's an issue coming from somewhere inside the `postgres` crate?

FWIW, here is the beginning of my test, which triggers the panic on the last quoted line, and `postgres --version` returns 14.6 on my (nixos) machine:
```rust
fn build_pg_cluster(data: &Path) -> postgresfixture::cluster::Cluster {
    let mut runtime = None;
    let mut best_version = None;
    for r in postgresfixture::runtime::Runtime::find_on_path() {
        if let Ok(v) = r.version() {
            match (&mut runtime, &mut best_version) {
                (None, None) => {
                    runtime = Some(r);
                    best_version = Some(v);
                }
                (Some(runtime), Some(best_version)) => {
                    if *best_version < v {
                        *runtime = r;
                        *best_version = v;
                    }
                }
                _ => unreachable!(),
            }
        }
    }
    postgresfixture::cluster::Cluster::new(
        data,
        runtime.expect("postgresql seems to not be installed in path"),
    )
}

// ..., inside a macro that generates my tests
        #[test]
        fn $name() {
            if std::env::var("RUST_LOG").is_ok() {
                tracing_subscriber::fmt::init();
            }
            let lockfile = tempfile::tempfile().expect("creating tempfile");
            let datadir = tempfile::tempdir().expect("creating tempdir");
            let datadir_path: &Path = datadir.as_ref();
            let cluster = build_pg_cluster(datadir_path);
            postgresfixture::coordinate::run_and_destroy(&cluster, lockfile.into(), || {
                cluster.createdb("test-db").expect("creating test-db db");
```

BTW, would it make sense to include this `build_pg_cluster` in `postgresfixture` itself, maybe as a `Runtime::find_latest_in_path() -> Option<Runtime>`?

**Comment by Ekleog** [comment]
Okeyyy turns out I'm stupid and it's just that `-` is not an allowed character in a db name. (Yes I had to reimplement `createdb` using `sqlx` in order to notice that it was weird that the error was almost the same).

I'm leaving open because I'm wondering whether it'd make sense to sanity-check that the passed db name would be accepted by postgres before passing it through? As the error is… pretty cryptic.

Feel free to close if you don't feel like it, I'd totally understand if this were out-of-scope :)

And with that said I can confirm that `postgresfixture` works for me! Though I'd still be able to take advantage of the improvements I listed in other issues and the PR :)

**Comment by allenap** [comment]
I don't want to reimplement PostgreSQL's validation, but I could use [`postgres_protocol::escape::escape_identifier`](https://docs.rs/postgres-protocol/latest/postgres_protocol/escape/fn.escape_identifier.html) so that the error message from PostgreSQL is more accurate.

**Comment by Ekleog** [comment]
Awesome, thank you! :D
